.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tale 1  "tale 0.1.0" 
.SH NAME
tale \- A terminal\-native Tailscale workspace
.SH SYNOPSIS
\fBtale\fR [\fB\-\-profile\fR] [\fB\-\-config\fR] [\fB\-\-view\fR] [\fB\-\-read\-only\fR] [\fB\-\-no\-local\fR] [\fB\-\-tailscale\-path\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
A terminal\-native Tailscale workspace
.SH OPTIONS
.TP
\fB\-\-profile\fR \fI<NAME>\fR

.TP
\fB\-\-config\fR \fI<PATH>\fR

.TP
\fB\-\-view\fR \fI<ROUTE>\fR

.TP
\fB\-\-read\-only\fR

.TP
\fB\-\-no\-local\fR

.TP
\fB\-\-tailscale\-path\fR \fI<PATH>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
tale\-auth(1)
.TP
tale\-config(1)
.TP
tale\-doctor(1)
.SH VERSION
v0.1.0
