use serde::{Deserialize, Serialize};

use crate::domain::Timestamp;
use crate::domain::device::{
    ConnectionPath, Device, DeviceCapabilities, DeviceId, Liveness, OperatingSystem,
};

pub const MOCK_NOW: Timestamp = 1_754_000_000;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Serialize, Deserialize)]
pub enum MockLoadScenario {
    Initial,
    Success,
    Failure,
    Stale,
}

pub type MockScenario = MockLoadScenario;

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum MockTaskBehavior {
    DelayedSuccess,
    DelayedFailure,
    CancellableLong,
    NonCancellable,
}

pub fn load_devices(scenario: MockLoadScenario) -> Result<(Vec<Device>, Timestamp), String> {
    match scenario {
        MockLoadScenario::Failure => {
            Err("mock refresh failed: fictional source timeout".to_owned())
        }
        MockLoadScenario::Stale => Ok((devices(), MOCK_NOW.saturating_sub(240))),
        MockLoadScenario::Initial | MockLoadScenario::Success => Ok((devices(), MOCK_NOW)),
    }
}

pub fn devices() -> Vec<Device> {
    vec![
        device(
            "dev-a01",
            "build-01",
            "build-01.example.com",
            Some("alice@example.com"),
            Some("Alice"),
            OperatingSystem::Linux,
            Liveness::Online,
            ConnectionPath::Direct {
                latency_ms: Some(18),
            },
            vec!["192.0.2.10", "2001:db8:42::10"],
            vec!["server", "prod"],
            Some(MOCK_NOW.saturating_sub(3)),
            DeviceCapabilities {
                exit_node: true,
                exit_node_option: false,
                subnet_router: true,
                ssh: true,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-b02",
            "studio-mac",
            "studio-mac.example.com",
            Some("alice@example.com"),
            Some("Alice"),
            OperatingSystem::MacOS,
            Liveness::Online,
            ConnectionPath::Derp {
                region: "fra".to_owned(),
            },
            vec!["192.0.2.11"],
            vec!["design"],
            Some(MOCK_NOW.saturating_sub(12)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: true,
                funnel: true,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-c03",
            "win-lab",
            "win-lab.example.com",
            Some("bob@example.com"),
            Some("Bob"),
            OperatingSystem::Windows,
            Liveness::Offline,
            ConnectionPath::PeerRelay {
                peer: "build-01".to_owned(),
            },
            vec!["192.0.2.12"],
            vec!["lab", "shared"],
            Some(MOCK_NOW.saturating_sub(7_200)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: true,
                ssh: false,
                funnel: false,
                shared: true,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-d04",
            "pocket",
            "pocket.example.com",
            Some("carol@example.com"),
            Some("Carol"),
            OperatingSystem::IOS,
            Liveness::Unknown,
            ConnectionPath::NoPath,
            Vec::new(),
            vec!["mobile"],
            None,
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: false,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-e05",
            "tablet",
            "tablet.example.com",
            Some("carol@example.com"),
            Some("Carol"),
            OperatingSystem::Android,
            Liveness::Online,
            ConnectionPath::Direct {
                latency_ms: Some(42),
            },
            vec!["198.51.100.5", "2001:db8:42::5"],
            vec!["mobile", "personal"],
            Some(MOCK_NOW.saturating_sub(60)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: false,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-f06",
            "edge-relay",
            "edge-relay.example.com",
            Some("dana@example.com"),
            Some("Dana"),
            OperatingSystem::Unknown("plan9".to_owned()),
            Liveness::Online,
            ConnectionPath::PeerRelay {
                peer: "build-01".to_owned(),
            },
            vec!["203.0.113.6"],
            vec!["relay", "edge"],
            Some(MOCK_NOW.saturating_sub(90)),
            DeviceCapabilities {
                exit_node: true,
                exit_node_option: false,
                subnet_router: true,
                ssh: true,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-g07",
            "archive-node-with-a-deliberately-long-fictional-name",
            "archive.example.com",
            Some("erin@example.com"),
            Some("Erin"),
            OperatingSystem::Linux,
            Liveness::Offline,
            ConnectionPath::Derp {
                region: "syd".to_owned(),
            },
            vec!["203.0.113.7"],
            vec!["archive"],
            Some(MOCK_NOW.saturating_sub(86_400)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: true,
                ssh: true,
                funnel: false,
                shared: false,
                expired: true,
                approved: true,
            },
        ),
        device(
            "dev-h08",
            "审批-标签",
            "pending.example.com",
            Some("faye@example.com"),
            Some("Faye"),
            OperatingSystem::Linux,
            Liveness::Unknown,
            ConnectionPath::NoPath,
            vec!["192.0.2.18"],
            vec!["pending", "新"],
            Some(MOCK_NOW.saturating_sub(400)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: false,
                funnel: false,
                shared: false,
                expired: false,
                approved: false,
            },
        ),
        device(
            "dev-i09",
            "funnel-demo",
            "funnel.example.com",
            Some("glen@example.com"),
            Some("Glen"),
            OperatingSystem::MacOS,
            Liveness::Online,
            ConnectionPath::Direct { latency_ms: None },
            vec!["198.51.100.9"],
            vec!["demo", "public"],
            Some(MOCK_NOW.saturating_sub(15)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: true,
                funnel: true,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-j10",
            "shared-laptop",
            "shared.example.com",
            None,
            Some("Shared workspace"),
            OperatingSystem::Windows,
            Liveness::Offline,
            ConnectionPath::Derp {
                region: "nyc".to_owned(),
            },
            Vec::new(),
            vec!["shared"],
            Some(MOCK_NOW.saturating_sub(12_000)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: false,
                funnel: false,
                shared: true,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-k11",
            "subnet-gateway",
            "gateway.example.com",
            Some("hugo@example.com"),
            Some("Hugo"),
            OperatingSystem::Linux,
            Liveness::Online,
            ConnectionPath::Direct {
                latency_ms: Some(7),
            },
            vec!["192.0.2.21", "2001:db8:42::21"],
            vec!["router", "office"],
            Some(MOCK_NOW.saturating_sub(5)),
            DeviceCapabilities {
                exit_node: true,
                exit_node_option: false,
                subnet_router: true,
                ssh: true,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-l12",
            "quiet-phone",
            "quiet-phone.example.com",
            Some("ivy@example.com"),
            Some("Ivy"),
            OperatingSystem::Android,
            Liveness::Offline,
            ConnectionPath::NoPath,
            vec!["192.0.2.22"],
            vec!["personal"],
            Some(MOCK_NOW.saturating_sub(172_800)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: false,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-m13",
            "relay-observer",
            "relay-observer.example.com",
            Some("jules@example.com"),
            Some("Jules"),
            OperatingSystem::Unknown("haiku".to_owned()),
            Liveness::Online,
            ConnectionPath::Derp {
                region: "ams".to_owned(),
            },
            vec!["203.0.113.13"],
            vec!["relay"],
            Some(MOCK_NOW.saturating_sub(33)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: true,
                funnel: false,
                shared: false,
                expired: false,
                approved: true,
            },
        ),
        device(
            "dev-n14",
            "approval-expired",
            "approval-expired.example.com",
            Some("kira@example.com"),
            Some("Kira"),
            OperatingSystem::IOS,
            Liveness::Unknown,
            ConnectionPath::NoPath,
            vec!["198.51.100.14"],
            vec!["expired", "approval"],
            Some(MOCK_NOW.saturating_sub(604_800)),
            DeviceCapabilities {
                exit_node: false,
                exit_node_option: false,
                subnet_router: false,
                ssh: false,
                funnel: false,
                shared: false,
                expired: true,
                approved: false,
            },
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
fn device(
    id: &str,
    display_name: &str,
    hostname: &str,
    owner: Option<&str>,
    owner_label: Option<&str>,
    os: OperatingSystem,
    liveness: Liveness,
    path: ConnectionPath,
    addresses: Vec<&str>,
    tags: Vec<&str>,
    last_seen: Option<Timestamp>,
    capabilities: DeviceCapabilities,
) -> Device {
    Device {
        id: DeviceId::new(id),
        display_name: display_name.to_owned(),
        hostname: hostname.to_owned(),
        owner: owner.map(str::to_owned),
        owner_label: owner_label.map(str::to_owned),
        os,
        version: "1.98.9".to_owned(),
        liveness,
        path,
        addresses: addresses.into_iter().map(str::to_owned).collect(),
        advertised_routes: Vec::new(),
        tags: tags.into_iter().map(str::to_owned).collect(),
        last_seen,
        created_at: Some(MOCK_NOW.saturating_sub(90 * 86_400)),
        rx_bytes: None,
        tx_bytes: None,
        capabilities,
    }
}
